name: Dan Fishbach
favicon: null
layout_spectrum: 0.14549794839695096
typography_spectrum: 0.47148949885740876
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8482831288129091
  lightness: 0.651649946346879
  saturation: 0.33585036755539477
  rhythmicContrast: 0.48171660187654197
purpose: []
